using TimeMasters.PortableClassLibrary.Helpers;

namespace TimeMasters.PortableClassLibrary.Translator
{
    public enum Languages
    {
        [StringValue("af")]
        Afrikaans = 0,
        [StringValue("ar")]
        Arabic,
        [StringValue("bs-Latn")]
        Bosnian,
        [StringValue("bg")]
        Bulgarian,
        [StringValue("ca")]
        Catalan,
        [StringValue("zh-CHS")]
        ChineseSimple,
        [StringValue("zh-CHT")]
        ChineseTraditional,
        [StringValue("hr")]
        Croatian,
        [StringValue("cs")]
        Czech,
        [StringValue("da")]
        Danish,
        [StringValue("nl")]
        Dutch,
        [StringValue("en")]
        English,
        [StringValue("et")]
        Estonian,
        [StringValue("fi")]
        Finnish,
        [StringValue("fr")]
        French,
        [StringValue("de")]
        German,
        [StringValue("el")]
        Greek,
        [StringValue("ht")]
        HaitianCreole,
        [StringValue("he")]
        Hebrew,
        [StringValue("hi")]
        Hindi,
        [StringValue("mww")]
        HmongDaw,
        [StringValue("hu")]
        Hungarian,
        [StringValue("id")]
        Indonesian,
        [StringValue("it")]
        Italian,
        [StringValue("Ja")]
        Japanese,
        [StringValue("sw")]
        Kiswahili,
        [StringValue("tlh")]
        Klingon,
        [StringValue("tlh-Qaak")]
        KlingonQaak,
        [StringValue("ko")]
        Korean,
        [StringValue("lv")]
        Latvian,
        [StringValue("lt")]
        Lithuanian,
        [StringValue("ms")]
        Malay,
        [StringValue("mt")]
        Maltese,
        [StringValue("no")]
        Norwegian,
        [StringValue("fa")]
        Persian,
        [StringValue("pl")]
        Polish,
        [StringValue("pt")]
        Portugese,
        [StringValue("otq")]
        QueretaroOtomi,
        [StringValue("ro")]
        Romanian,
        [StringValue("ru")]
        Russian,
        [StringValue("sr-Cyrl")]
        SerbianCyrillic,
        [StringValue("sr-Latn")]
        SerbianLatin,
        [StringValue("sk")]
        Slovak,
        [StringValue("sl")]
        Slovanian,
        [StringValue("es")]
        Spanish,
        [StringValue("sv")]
        Swedish,
        [StringValue("th")]
        Thai,
        [StringValue("tr")]
        Turkish,
        [StringValue("uk")]
        Ukranian,
        [StringValue("ur")]
        Urdu,
        [StringValue("vi")]
        Vietnamese,
        [StringValue("cy")]
        Welsh,
        [StringValue("yua")]
        YucatecMaya
    }
}